//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_dpadClick : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean dpadUp
        {
            get
            {
                return SteamVR_Actions.dpadClick_dpadUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean dpadDown
        {
            get
            {
                return SteamVR_Actions.dpadClick_dpadDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean dpadLeft
        {
            get
            {
                return SteamVR_Actions.dpadClick_dpadLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean dpadRight
        {
            get
            {
                return SteamVR_Actions.dpadClick_dpadRight;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.dpadClick_pose;
            }
        }
    }
}
